### ----------------------------------------------------------------- VEHICLES AND ISSUES
### get vehicles
GET http://localhost:3000/team1/api/vehicles
Authorization: Zb84MzAROCrhmF6t

### get vehicles sort
GET http://localhost:3000/team1/api/vehicles?sort=model&direction=asc
Authorization: Zb84MzAROCrhmF6t

### delete a vehicle
GET http://localhost:3000/team1/api/vehicles/504
Authorization: Zb84MzAROCrhmF6t

### create vehicle
POST http://localhost:3000/team1/api/vehicles
Content-Type: application/json
Authorization: Zb84MzAROCrhmF6t

{
  "model": "AN-12",
  "manufacture_year": "2022-01-20",
  "plate_number": "BV9123V",
  "engine_number": "1992312309GJAK1293",
  "fuel_type": "diesel"
}

### update vehicle
PUT http://localhost:3000/team1/api/vehicles/100
Content-Type: application/json

{
  "model": "AN-12345",
  "manufacture_year": "2022-01-20",
  "plate_number": "BV9123V",
  "engine_number": "1992312309GJAK1293",
  "fuel_type": "gasoline"
}

### get issues of a vehicle
GET http://localhost:3000/team1/api/vehicles/507/issues
Content-Type: application/json
Authorization: Zb84MzAROCrhmF6t

### create a new issue for a vehicle
POST http://localhost:3000/team1/api/vehicles/507/issues
Content-Type: application/json
Authorization: Zb84MzAROCrhmF6t

{
  "description":  "Change oil",
  "priority": "low",
  "due_date":  "2023-12-31"
}

### complete an issue
PATCH http://localhost:3000/team1/api/vehicles/507/issues/502/complete
Content-Type: application/json
Authorization: Zb84MzAROCrhmF6t

### Delete an issue
DELETE http://localhost:3000/team1/api/vehicles/100/issues/501

### ----------------------------------------------------------------- VEHICLES AND ISSUES




### ----------------------------------------------------------------- DRIVERS AND TRIPS
### get drivers
GET http://localhost:3000/team1/api/drivers
Authorization: Zb84MzAROCrhmF6t

### create driver
POST http://localhost:3000/team1/api/drivers
Content-Type: application/json
Authorization: Zb84MzAROCrhmF6t

{
  "first_name": "Ales",
  "last_name": "Jones",
  "birth_date": "1985-01-15",
  "email": "tom@figaro.com",
  "phone_number": "+14372394298",
  "address1": "12 James St",
  "address2": null,
  "city": "Vancouver",
  "state": "BC",
  "postal_code": "V3J0K5",
  "country": "Canada",
  "license_number": "BV01291",
  "license_class": "5"
}

### update driver
PUT http://localhost:3000/team1/api/drivers/2501
Content-Type: application/json

{
  "first_name": "Alex",
  "last_name": "Jones",
  "birth_date": "1985-01-15",
  "email": "tom@figaro.com",
  "phone_number": "+14372394298",
  "address1": "12 James St",
  "address2": null,
  "city": "Vancouver",
  "state": "BC",
  "postal_code": "V3J0K5",
  "country": "Canada",
  "license_number": "BV01291",
  "license_class": "5"
}

### get driver's trips
GET http://localhost:3000/team1/api/drivers/83/trips
Authorization: Zb84MzAROCrhmF6t

### create a new trip
POST http://localhost:3000/team1/api/drivers/2501/trips
Content-Type: application/json

{
  "vehicle_id": "99",
  "departure_location": "Chicago",
  "arrival_location": "New York",
  "start_date": "2023-12-15",
  "end_date": "2023-12-20",
  "distance": "1000 miles",
  "duration": "25 hours"
}

### complete a trip
PATCH http://localhost:3000/team1/api/drivers/83/trips/68/complete
Authorization: Zb84MzAROCrhmF6t
Content-Type: application/json

### ----------------------------------------------------------------- DRIVERS
















### create unassignment
POST http://localhost:3000/team1/api/vehicles/201/unassign
Content-Type: application/json

{
  "assignment_id": "19",
  "assignment": {
    "end_odometer": "200",
    "end_date":  "2023-02-05",
    "end_comment": "Finish it!"
  }
}